import type { Doctor } from "@/types/doctor";

export const doctors: Doctor[] = [
  {
    id: "doc-anika-rao",
    name: "Dr. Anika Rao",
    initials: "AR",
    specialty: "General medicine",
    credentials: "MBBS, MD",
    yearsExperience: 11,
    languages: ["English", "Hindi"],
    clinic: "Room 04 · Ground floor",
    bio: "Sees adults for everyday illness, chronic condition follow-ups, and annual wellness checks.",
    consultFee: 600,
  },
  {
    id: "doc-martin-cole",
    name: "Dr. Martin Cole",
    initials: "MC",
    specialty: "Dermatology",
    credentials: "MBBS, DVD",
    yearsExperience: 8,
    languages: ["English"],
    clinic: "Room 12 · First floor",
    bio: "Treats skin, hair, and nail conditions, from acne and eczema to mole checks.",
    consultFee: 800,
  },
  {
    id: "doc-lena-souza",
    name: "Dr. Lena Souza",
    initials: "LS",
    specialty: "Pediatrics",
    credentials: "MBBS, MD (Peds)",
    yearsExperience: 14,
    languages: ["English", "Portuguese"],
    clinic: "Room 07 · Ground floor",
    bio: "Cares for infants through teens, including vaccinations and growth check-ins.",
    consultFee: 700,
  },
  {
    id: "doc-imran-siddiqui",
    name: "Dr. Imran Siddiqui",
    initials: "IS",
    specialty: "Cardiology",
    credentials: "MBBS, DM (Cardiology)",
    yearsExperience: 17,
    languages: ["English", "Hindi", "Urdu"],
    clinic: "Room 21 · Second floor",
    bio: "Manages hypertension, arrhythmia, and post-cardiac-event recovery plans.",
    consultFee: 1200,
  },
  {
    id: "doc-hana-kim",
    name: "Dr. Hana Kim",
    initials: "HK",
    specialty: "Orthopedics",
    credentials: "MBBS, MS (Ortho)",
    yearsExperience: 9,
    languages: ["English", "Korean"],
    clinic: "Room 15 · First floor",
    bio: "Treats joint pain, sports injuries, and post-fracture rehabilitation.",
    consultFee: 900,
  },
  {
    id: "doc-owen-fischer",
    name: "Dr. Owen Fischer",
    initials: "OF",
    specialty: "General medicine",
    credentials: "MBBS",
    yearsExperience: 5,
    languages: ["English", "German"],
    clinic: "Room 05 · Ground floor",
    bio: "New-patient intakes, minor urgent care, and referrals to specialists.",
    consultFee: 500,
  },
];
